# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TC Myths
owner_name: Bob Watson
email: tcmyths@tcmyths.com
lang: en-US
description: All technical communication myths in place.
# URLS used in the docs will always start with a slash
#  URL variables should, therefore, NEVER end with a slash character
url: https://tcmyths.com # the base hostname & protocol for your site
baseurl:  # the subpath of your site, e.g. /blog
mybaseurl:  # defined to have a base url variable that isn't used for something else by Jekyll
twitter_username: bobwatsonphd
github_username:  tcmyths
google_analytics: UA-58134115-2
# comments: false		# comments disabled for now
comments: true		# comments enabled for testing
#
#	These collections contain the site content
#		myths contains the myth topics
#		refs contains the source reference topics
#
collections:
  myths:
    output: true
  refs:
    output: true
author:
  name: Bob Watson
  url: https://docsbydesign.com

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
